<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>111f0f83-0963-411b-9131-b01f59321f6f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PedrosCantinaLibrary\PedrosCantinaLibrary.csproj" />
  </ItemGroup>

</Project>
